cybersecurity_words = [
    ("Firewall", "It acts as a barrier between your network and potential threats."),
    ("Malware", "It's malicious software that can harm your system."),
    ("Encryption", "It involves converting your data into a secret code."),
    ("Phishing", "Often comes in the form of deceptive emails."),
    ("Vulnerability", "It's a weakness in your system that hackers can exploit."),
    ("Password", "Key to your online life."),
    ("Patch", "Used to fix vulnerabilities in software."),
    ("DDoSAttack", "Overwhelms a system with a flood of data."),
    ("Virus", "A type of malware that spreads by infecting other files."),
    ("Worm", "Self-replicating malware that spreads across networks."),
    ("Authentication", "Verifying the identity of a user, device, or system."),
    ("Hacker", "An individual who seeks unauthorized access to systems."),
    ("Ransomware", "Software that locks your files and demands a ransom for their release."),
    ("Trojan", "Malicious software disguised as legitimate software to gain unauthorized access."),
    ("Rootkit", "A set of software tools that grants unauthorized access to a computer system."),
    ("Botnet", "A network of infected computers controlled by a single entity, often used for malicious purposes."),
    ("BruteForce", "A hacking method that involves trying all possible combinations to crack passwords or encryption."),
    ("ZeroDay", "An undisclosed software vulnerability that hackers can exploit before a patch is available."),
    ("SSL", "Secure Sockets Layer, a protocol that ensures secure data transmission over the internet."),
    ("Pharming", "Redirecting website traffic to a fraudulent site to steal sensitive information."),
    ("Cryptocurrency", "Digital or virtual currencies that use cryptography for security."),
    ("Biometrics", "Authentication based on unique physical or behavioral characteristics, like fingerprints or iris scans."),
    ("Cyberattack", "Malicious actions intended to compromise or disrupt computer systems or networks."),
    ("IncidentResponse", "The process of managing and mitigating the aftermath of a cybersecurity incident."),
    ("Antivirus", "Software designed to detect, prevent, and remove malicious software from a computer."),
]
